"""
memory.py — Case-based long-term memory for Smart Mirror exercise coaching.

Two stores:
  user_memory.json  — persona + session cases (one entry per completed session,
                      each storing joint stats + the feedback the agent gave)
  trend_log.jsonl   — append-only, one line per session: the trend observation
                      the agent generated by comparing current vs previous sessions.
                      Kept separate from the case-base so it never inflates memory size.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

ROOT        = Path(__file__).parent
MEMORY_FILE = ROOT / "user_memory.json"
TREND_LOG   = ROOT / "trend_log.jsonl"

_BLANK: dict = {
    "persona": {
        "name":      None,
        "age":       None,
        "gender":    None,
        "condition": None,   # e.g. "frozen left shoulder", "post-chemo fatigue"
        "notes":     None,   # any other relevant info
    },
    "sessions": [],          # list of session cases, oldest first
}


# ── Internal I/O ──────────────────────────────────────────────────────────────

def _load() -> dict:
    if MEMORY_FILE.exists():
        try:
            return json.loads(MEMORY_FILE.read_text())
        except Exception:
            pass
    import copy
    return copy.deepcopy(_BLANK)


def _save(data: dict) -> None:
    MEMORY_FILE.write_text(json.dumps(data, indent=2))


# ── Persona ───────────────────────────────────────────────────────────────────

def get_persona() -> dict:
    """Return the stored user persona dict."""
    return _load()["persona"]


def update_persona(
    name:      Optional[str] = None,
    age:       Optional[int] = None,
    gender:    Optional[str] = None,
    condition: Optional[str] = None,
    notes:     Optional[str] = None,
) -> dict:
    """Update any persona fields that are provided (None = leave unchanged)."""
    mem = _load()
    p   = mem["persona"]
    if name      is not None: p["name"]      = name
    if age       is not None: p["age"]       = int(age)
    if gender    is not None: p["gender"]    = gender
    if condition is not None: p["condition"] = condition
    if notes     is not None: p["notes"]     = notes
    _save(mem)
    return p


# ── Session cases ─────────────────────────────────────────────────────────────

def add_session(
    session_file:    str,
    joint_stats:     dict,
    total_frames:    int,
    angle_threshold: int,
    feedback_given:  str,
    exercise_name:   str = "Exercise session",
) -> dict:
    """
    Append a completed session to the case-base.

    joint_stats format:
      {
        "right_shoulder": {"bad_pct": 18.6, "mean_diff": -10.0, "max_abs_diff": 150},
        ...
      }
    Returns the newly created case dict.
    """
    mem = _load()
    now = datetime.now()
    case = {
        "id":               now.strftime("%Y-%m-%d_%H%M%S"),
        "date":             now.strftime("%Y-%m-%d"),
        "day_of_week":      now.strftime("%A"),
        "exercise_name":    exercise_name,
        "session_file":     session_file,
        "total_frames":     total_frames,
        "angle_threshold":  angle_threshold,
        "joint_stats":      joint_stats,
        "feedback_given":   feedback_given,
    }
    mem["sessions"].append(case)
    _save(mem)
    return case


def get_sessions(n: int = 10) -> list[dict]:
    """Return the last *n* session cases, oldest first."""
    return _load()["sessions"][-n:]


# ── Trend log ─────────────────────────────────────────────────────────────────

def append_trend_entry(entry: dict) -> None:
    """
    Append one trend observation (dict) to trend_log.jsonl with a timestamp.
    Each line is self-contained JSON so the file stays readable as it grows.
    """
    entry["logged_at"] = datetime.now().isoformat(timespec="seconds")
    with open(TREND_LOG, "a") as fh:
        fh.write(json.dumps(entry) + "\n")


# Keep old name as alias so nothing else breaks
def append_trend(session_id: str, trend_text: str) -> None:
    append_trend_entry({"session_id": session_id, "trend": trend_text})
